export {
  getAdminAdvancedPageCopy,
  getAdminAppearancePageCopy,
  getAdminAuditLogsPageCopy,
  getAdminBasicsPageCopy,
  getAdminMailPageCopy,
  getAdminPageCopy,
  getAdminPermissionsPageCopy,
  getAdminUsersPageCopy,
  registerAdminAdvancedPageCopy,
  registerAdminAppearancePageCopy,
  registerAdminAuditLogsPageCopy,
  registerAdminBasicsPageCopy,
  registerAdminMailPageCopy,
  registerAdminPageCopy,
  registerAdminPermissionsPageCopy,
  registerAdminUsersPageCopy,
} from './pageCopies.js'
export {
  getAdminAdvancedPageConfig,
  getAdminAppearancePageConfig,
  getAdminAuditLogsPageConfig,
  getAdminBasicsPageConfig,
  getAdminMailPageConfig,
  getAdminPageConfig,
  getAdminPermissionsPageConfig,
  getAdminUsersPageConfig,
  registerAdminAdvancedPageConfig,
  registerAdminAppearancePageConfig,
  registerAdminAuditLogsPageConfig,
  registerAdminBasicsPageConfig,
  registerAdminMailPageConfig,
  registerAdminPageConfig,
  registerAdminPermissionsPageConfig,
  registerAdminUsersPageConfig,
} from './pageConfigs.js'
export {
  getAdminAdvancedPageActionMeta,
  getAdminAppearancePageActionMeta,
  getAdminBasicsPageActionMeta,
  getAdminMailPageActionMeta,
  getAdminPageActionMeta,
  getAdminPermissionsPageActionMeta,
  getAdminUsersPageActionMeta,
  registerAdminAdvancedPageActionMeta,
  registerAdminAppearancePageActionMeta,
  registerAdminBasicsPageActionMeta,
  registerAdminMailPageActionMeta,
  registerAdminPageActionMeta,
  registerAdminPermissionsPageActionMeta,
  registerAdminUsersPageActionMeta,
} from './pageActionMeta.js'
export {
  getAdminAppearancePageAction,
  getAdminAppearancePageActions,
  getAdminMailPageAction,
  getAdminMailPageActions,
  getAdminPageAction,
  getAdminPageActions,
  registerAdminAppearancePageAction,
  registerAdminMailPageAction,
  registerAdminPageAction,
} from './pageActions.js'
export {
  getAdminPageNoteTemplates,
  registerAdminPageNoteTemplate,
} from './pageNoteTemplates.js'
