import {
  registerAdminAdvancedPageActionMeta,
  registerAdminAdvancedPageConfig,
  registerAdminAdvancedPageCopy,
} from '../pages.js'

registerAdminAdvancedPageCopy({
  key: 'core-advanced-page-copy',
  order: 10,
  resolve: () => ({
    pageTitle: '高级设置',
    pageDescription: '配置缓存、队列、维护模式和运行时诊断',
    runtimeNoticeTitle: '运行时说明',
    immediateEffectTitle: '即时生效',
    immediateEffectDescription: '`maintenance_mode`、`maintenance_message`、`cache_lifetime`、`log_queries` 会在保存后直接影响请求层行为。',
    deploymentRequiredTitle: '需额外部署或重启',
    deploymentRequiredDescription: '`debug_mode` 由 Django 配置文件或环境变量控制；`queue_enabled` / `queue_driver` 会控制已接入队列入口的任务，新 worker 配置需重启服务后生效。',
    dependencyHealthTitle: '依赖健康',
    dependencyHealthHelpText: '查看缓存、实时层、队列 broker 与 worker 的当前运行状态。',
    dependencyActionLabel: '建议处理',
    cacheSectionTitle: '缓存设置',
    cacheDriverLabel: '缓存驱动',
    cacheDriverHelpText: '选择缓存存储方式',
    cacheLifetimeLabel: '缓存时间（秒）',
    cacheLifetimeHelpText: '当前已接入公开论坛设置缓存。填 0 表示禁用该缓存，保存基础/外观/高级设置时会自动清理。',
    clearCacheLabel: '清除缓存',
    clearingCacheLabel: '清除中...',
    searchStatusLoadingText: '加载中...',
    queueSectionTitle: '队列设置',
    queueDriverLabel: '队列驱动',
    queueDriverHelpText: '当前通知实时投递已接入统一队列入口。选择 Redis 并部署 worker 后会尝试异步投递。',
    queueEnabledLabel: '启用队列处理',
    queueEnabledHelpText: '关闭时强制同步执行。开启后，已接入任务会入队执行；入队失败时会同步回退，避免影响主流程。',
    maintenanceSectionTitle: '维护模式',
    maintenanceEnabledLabel: '启用维护模式',
    maintenanceEnabledHelpText: '启用后，普通用户访问论坛 API 将收到 503；`/api/forum`、登录接口和后台入口保留豁免。',
    maintenanceMessageLabel: '维护提示信息',
    extensionSafeModeLabel: '启用扩展恢复模式',
    extensionSafeModeHelpText: '启用后只启动核心能力和白名单扩展，用于排查扩展导致的启动或运行异常。',
    extensionSafeModeExtensionsLabel: '恢复模式扩展白名单',
    extensionSafeModeExtensionsHelpText: '填写扩展 ID，多个扩展用英文逗号分隔。留空时只启动核心能力。',
    debugSectionTitle: '调试设置',
    debugModeLabel: '调试模式（只读）',
    debugModeHelpText: '当前运行值来自 Django 配置文件或环境变量，保存这里不会热切换服务端 DEBUG。',
    logQueriesLabel: '记录数据库查询',
    logQueriesHelpText: '保存后即时生效。会把每个 HTTP 请求触发的 SQL 记录到服务器日志。',
    saveLabel: '保存设置',
    savingLabel: '保存中...',
    saveSuccessText: '保存成功',
    saveErrorText: '保存失败，请重试',
  }),
})

registerAdminAdvancedPageConfig({
  key: 'core-advanced-page-config',
  order: 10,
  resolve: () => ({
    defaultSettings: {
      cache_driver: 'file',
      cache_lifetime: 3600,
      queue_driver: 'sync',
      queue_enabled: false,
      maintenance_mode: false,
      maintenance_mode_key: 'none',
      maintenance_message: '',
      extension_safe_mode: false,
      extension_safe_mode_extensions: [],
      debug_mode: false,
      log_queries: false,
    },
    defaultRuntimeDependencyChecks: [],
    placeholders: {
      cacheLifetime: '3600',
      maintenanceMessage: '论坛正在维护中，请稍后再试...',
      extensionSafeModeExtensions: 'tags, notifications',
    },
    cacheDriverOptions: [
      { value: 'file', label: '文件' },
      { value: 'redis', label: 'Redis' },
      { value: 'memcached', label: 'Memcached' },
    ],
    queueDriverOptions: [
      { value: 'sync', label: '同步' },
      { value: 'database', label: '数据库' },
      { value: 'redis', label: 'Redis' },
    ],
    maintenanceModeOptions: [
      { value: 'none', label: '关闭' },
      { value: 'low', label: '低维护' },
      { value: 'high', label: '高维护' },
      { value: 'safe', label: '恢复模式' },
    ],
    sensitiveLabels: {
      maintenance_mode: '维护模式',
      maintenance_mode_key: '维护级别',
      extension_safe_mode: '扩展恢复模式',
      extension_safe_mode_extensions: '恢复模式扩展白名单',
      queue_enabled: '队列启用状态',
      queue_driver: '队列驱动',
      log_queries: 'SQL 查询日志',
    },
  }),
})

registerAdminAdvancedPageActionMeta({
  key: 'core-advanced-page-actions-meta',
  order: 10,
  resolve: () => ({
    loadErrorText: '加载高级设置失败，请稍后重试',
    saveConfirmTitle: '保存高级设置',
    saveConfirmMessage: changes => `以下设置会影响运行时行为：${changes.join('、')}。确定保存当前配置吗？`,
    saveConfirmText: '保存',
    saveCancelText: '取消',
    clearCacheConfirmTitle: '清除缓存',
    clearCacheConfirmMessage: '确定清除运行时缓存吗？短时间内部分页面可能重新读取配置和数据。',
    clearCacheConfirmText: '清除',
    clearCacheCancelText: '取消',
    clearCacheSuccessTitle: '缓存已清除',
    clearCacheSuccessMessage: '运行时缓存已成功清理。',
    clearCacheFailedTitle: '清除缓存失败',
    unknownErrorText: '未知错误',
  }),
})
