import {
  registerAdminAuditLogsPageConfig,
  registerAdminAuditLogsPageCopy,
} from '../pages.js'

registerAdminAuditLogsPageCopy({
  key: 'core-audit-logs-page-copy',
  order: 10,
  resolve: () => ({
    pageTitle: '审计日志',
    pageDescription: '查看管理员关键操作记录',
    actionFilterLabel: '筛选操作',
    targetFilterLabel: '筛选对象',
    allActionsLabel: '全部操作',
    allTargetsLabel: '全部对象',
    refreshLabel: '刷新',
    loadingText: '加载中...',
    loadErrorText: '加载审计日志失败',
    emptyText: '暂无审计日志',
    tableTimeHeader: '时间',
    tableUserHeader: '管理员',
    tableActionHeader: '操作',
    tableTargetHeader: '对象',
    tableSourceHeader: '来源',
    tableDetailHeader: '详情',
    timeLabel: '时间',
    userLabel: '管理员',
    actionLabel: '操作',
    targetLabel: '对象',
    sourceLabel: '来源',
    detailLabel: '详情',
    systemUserLabel: '系统',
    unknownActionLabel: '未知操作',
  }),
})

registerAdminAuditLogsPageConfig({
  key: 'core-audit-logs-page-config',
  order: 10,
  resolve: () => ({
    actionLabels: {
      'admin.appearance_asset.upload': '上传外观资源',
      'admin.approval.approve': '审核通过',
      'admin.approval.reject': '审核拒绝',
      'admin.cache.clear': '清除缓存',
      'admin.discussion.delete': '删除讨论',
      'admin.discussion.hide': '隐藏讨论',
      'admin.discussion.lock': '锁定讨论',
      'admin.discussion.restore': '恢复讨论',
      'admin.discussion.sticky': '置顶讨论',
      'admin.discussion.unlock': '解锁讨论',
      'admin.discussion.unsticky': '取消置顶',
      'admin.flag.resolve': '处理举报',
      'admin.group.create': '创建用户组',
      'admin.group.delete': '删除用户组',
      'admin.group.update': '更新用户组',
      'admin.mail.test': '发送测试邮件',
      'admin.permissions.update': '更新权限',
      'admin.post.delete': '删除回复',
      'admin.post.hide': '隐藏回复',
      'admin.post.restore': '恢复回复',
      'admin.queue_metrics.reset': '重置队列指标',
      'admin.search_indexes.rebuild': '重建搜索索引',
      'admin.settings.update': '更新设置',
      'admin.tag.create': '创建标签',
      'admin.tag.delete': '删除标签',
      'admin.tag.move': '移动标签',
      'admin.tag.refresh_stats': '刷新标签统计',
      'admin.tag.update': '更新标签',
      'admin.user.delete': '删除用户',
      'admin.user.update': '更新用户',
    },
    targetLabels: {
      appearance_asset: '外观资源',
      cache: '缓存',
      discussion: '讨论',
      group: '用户组',
      mail: '邮件',
      search_index: '搜索索引',
      permissions: '权限',
      post: '回复',
      post_flag: '举报',
      settings: '设置',
      tag: '标签',
      user: '用户',
    },
  }),
})
